language: c
script: ./travis-tool.sh run_tests
before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
- sudo apt-get update -qq
- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_deps
- Rscript -e 'download.file("http://www.omegahat.org/Prerelease/XMLSchema_0.8-0.tar.gz", "XMLSchema")'
- Rscript -e 'install.packages("XMLSchema", type="source", repos = NULL)'
- Rscript -e 'download.file("http://www.omegahat.org/Prerelease/SSOAP_0.91-0.tar.gz", "SSOAP")'
- Rscript -e 'install.packages("SSOAP", type="source", repos = NULL)'
notifications:
 slack: ropensci:wh30e1MP9Am3wXb2wJx1ZRFi
