language: r
sudo: required

after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - jimhester/covr
  - jeroenooms/curl

# print timings (of examples) and sysinfo
after_script:
  - dump_logs_by_extension "timings"
  - dump_sysinfo

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
    - _R_CHECK_TIMINGS_="0"
